### ISSUE TITLE
closeNav Btn color is not changing correctly with the theme switch

### ISSUE THREAD

**Issue by hunter6430** [MXHML/AP_COLLAB_PRJ#3]
When the program starts, close nav button color is white, but when change theme is selected the color remains white even though everything else is changing properly. Once it is clicked again then the color is changed to black and is the same color as the nav background color. I tried changing the style changes in the themes but it still is doing the same thing whether the color is changed from black to white.

**Comment by MXHML** [comment]
Close nav btn was a P element, when the queryselectorall found it, it was changing it to the wrong color.

**Comment by MXHML** [comment]
Changed the close button to an "a" element, so the styling is a little wonky if you want to fix it.
